from sqlalchemy import Column, Integer, String, DateTime, Numeric
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Ctc(Base):
    # Apontamento Cross-Database (Banco 'intec', schema 'dbo', tabela 'tb_ctc_esp')
    __tablename__ = 'tb_ctc_esp'
    __table_args__ = {'schema': 'intec.dbo'}
    
    # --- Chaves Primárias ---
    # Ajustado conforme sua indicação: 'filialctc' é o número do documento
    filial = Column(String(2), primary_key=True)
    filialctc = Column(String(10), primary_key=True) # Este é o número do CTC
    seriectc = Column(String(3), primary_key=True)

    # --- Mapeamento das Colunas (Sem a coluna 'ctc' que não existe) ---
    tipodoc = Column(String(3))
    tipoCTR = Column(String(5))
    motivodoc = Column(String(3))
    origem = Column(String(12))
    codfilial = Column(String(2))
    # filialctc (Já mapeado na PK)
    # filial (Já mapeado na PK)
    # seriectc (Já mapeado na PK)
    
    # OBS: Removi a coluna 'ctc' pois ela não existe na planilha original
    
    data = Column(DateTime)
    hora = Column(String(5))
    emissor = Column(String(20))
    conferente = Column(String(15))
    prioridade = Column(String(15))
    controleRU = Column(String(10))
    prev_entrega = Column(DateTime)
    prev_entregatipo = Column(String(1))
    rotafilialdest = Column(String(12))
    descr_rotafilial = Column(String(20))
    ctcpago = Column(String(1))
    remet_cgc = Column(String(14))
    remet_nome = Column(String(40))
    remet_end = Column(String(40))
    remet_cidade = Column(String(35))
    remet_uf = Column(String(2))
    remet_cep = Column(String(8))
    remet_ie = Column(String(15))
    respons_cgc = Column(String(14))
    respons_nome = Column(String(40))
    respons_end = Column(String(40))
    respons_cidade = Column(String(35))
    respons_uf = Column(String(2))
    respons_ie = Column(String(15))
    dest_cgc = Column(String(14))
    dest_nome = Column(String(40))
    dest_end = Column(String(40))
    dest_cidade = Column(String(35))
    dest_uf = Column(String(3))
    dest_cep = Column(String(8))
    dest_ie = Column(String(15))
    cidade_orig = Column(String(35))
    uf_orig = Column(String(2))
    via = Column(String(3))
    cidade_dest = Column(String(35))
    uf_dest = Column(String(2))
    regiao = Column(String(15))
    regiaogeo = Column(String(20))
    regiaosac = Column(String(2))
    atendsac = Column(String(10))
    nfs = Column(String(600))
    valmerc = Column(Numeric)
    peso = Column(Numeric)
    pesotax = Column(Numeric)
    volumes = Column(Integer)
    especie = Column(String(20))
    natureza = Column(String(25))
    naturezaobs = Column(String(25))
    dimensoes = Column(String(29))
    tabfrete = Column(String(7))
    tabfretedescr = Column(String(100))
    cfop = Column(String(4))
    fretepeso = Column(Numeric)
    fretepesobr = Column(Numeric)
    fretevalor = Column(Numeric)
    fretevalorbr = Column(Numeric)
    gris = Column(Numeric)
    grisbr = Column(Numeric)
    txentregared = Column(Numeric)
    txentregaredbr = Column(Numeric)
    txurgencia = Column(Numeric)
    txurgenciabr = Column(Numeric)
    pedagio = Column(Numeric)
    pedagiobr = Column(Numeric)
    txcoleta = Column(Numeric)
    txcoletabr = Column(Numeric)
    txoutros = Column(Numeric)
    txoutrosbr = Column(Numeric)
    descrtxoutros = Column(String(20))
    fretetotal = Column(Numeric)
    fretetotalbruto = Column(Numeric)
    fretefinal = Column(Numeric)
    fretepagosub = Column(Numeric)
    tribut = Column(String(1))
    aliquota = Column(Numeric)
    subtrib = Column(String(1))
    obs_fiscal = Column(String(50))
    subcontratacao = Column(String(1))
    filialmanifesto = Column(String(8))
    fpag = Column(String(7))
    faturar = Column(String(1))
    nservico = Column(String(1))
    nserviconum = Column(String(10))
    faturanum = Column(String(10))
    entrega_data = Column(DateTime)
    recebedor = Column(String(15))
    entrega_hora = Column(String(5))
    modal = Column(String(15))
    obs_emissao = Column(String(2000))
    obs_ocorr = Column(String(186))
    arq = Column(String(12))
    tem_ocorr = Column(String(1))
    redesp_cgc = Column(String(14))
    redesp_nome = Column(String(40))
    transp_sub = Column(String(20))
    cancelado = Column(String(1))
    canc_data = Column(DateTime)
    canc_usu = Column(String(10))
    canc_obs = Column(String(500))
    at_ctc_cif = Column(String(1))
    at_ctc_cif_data = Column(DateTime)
    codevo = Column(Integer)
    at_dispara = Column(String(1))
    at_cliente = Column(String(1))
    at_edi = Column(String(1))
    at_edi_data = Column(DateTime)
    at_edisub = Column(String(1))
    datalimiteembarque = Column(DateTime)
    impresso = Column(String(1))
    impresso_data = Column(DateTime)
    impresso_usu = Column(String(10))
    reimpr = Column(String(1))
    reimpr_data = Column(DateTime)
    reimpr_usu = Column(String(10))
    status = Column(String(1))
    edi_nfsitla = Column(String(1))
    edi_nfsitladata = Column(DateTime)
    ordem = Column(DateTime)
    qtdenfs = Column(Numeric)
    ValorICMS = Column(Numeric)
    pesotaxCTR03 = Column(Numeric)
    volumesCTR03 = Column(Numeric)
    fretepesoCTR03 = Column(Numeric)
    fretevalorCTR03 = Column(Numeric)
    grisCTR03 = Column(Numeric)
    txentregaredCTR03 = Column(Numeric)
    txurgenciaCTR03 = Column(Numeric)
    pedagioCTR03 = Column(Numeric)
    txcoletaCTR03 = Column(Numeric)
    txoutrosCTR03 = Column(Numeric)
    VersaoSistema = Column(String(20))
    fretetotalCTR03 = Column(Numeric)
    fretetotalbrutoCTR03 = Column(Numeric)
    cgc_dest = Column(String(14))
    nome_dest = Column(String(40))
    cep_dest = Column(String(8))
    end_dest = Column(String(40))
    Ctc_comp = Column(String(1))
    Filialctc_Origem = Column(String(10))
    GeraDesconto = Column(String(1))
    prefixo = Column(String(4))
    valmercCTR03 = Column(Numeric)
    end_coleta = Column(String(40))
    cid_coleta = Column(String(35))
    uf_coleta = Column(String(2))
    cep_coleta = Column(String(8))
    Codigo_ClienteEdiLog = Column(Integer)